# Generated by Django 5.2.8 on 2026-01-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sperra_app', '0002_teammember_alter_blog_description_alter_blog_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person giving the testimonial', max_length=100)),
                ('image', models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='testimonials/')),
                ('review', models.TextField(help_text='Customer or client review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['-created_at'],
            },
        ),
    ]
