# Generated by Django 5.2 on 2026-01-14 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sperra_app', '0007_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email',
        ),
    ]
