# Generated by Django 5.2 on 2026-01-16 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sperra_app', '0008_remove_appointment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
    ]
